name: on-demand-validate-pr
on:
    pull_request:
        branches: [release]
    workflow_dispatch:
        inputs:
            branch:
                description: 'Select Branch to validate'
                required: true
                type: choice
                default: release
                options:
                    - release
                    - preprod

jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            - name: task1
              run: |
                echo "Your Current branch in prepare job is: ${{inputs.branch}}"

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: task2
              run: |
                echo "Your Current branch in deploy job is: ${{inputs.branch}}"
